# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TRIGGERcmd
version: "1.0.2"
slug: triggercmd
description: Run commands on your computers via TRIGGERcmd.com
url: "https://github.com/rvmey/tcmd-homeassistant/tree/main/triggercmd"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  token: null
schema:
  token: "password?"
homeassistant_api: true
hassio_api: true
# image: "ghcr.io/rvmey/{arch}-triggercmd"
